import { useState, useRef, useEffect } from 'react';
import { useReading } from '@/contexts/ReadingContext';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { RefreshCw, BarChart2, MicIcon, Volume2 } from 'lucide-react';
import { generateReadingContent } from '@/lib/openai';
import { useToast } from '@/hooks/use-toast';
import { useDifficulty, mapDifficultyToServer, DifficultyLevel } from '@/contexts/DifficultyContext';
import useEnhancedVoice from '@/hooks/useEnhancedVoice';

// Define the props for ReadingContent component
interface ReadingContentProps {
  onSelectContent: () => void;
}

const ReadingContent = ({ onSelectContent }: ReadingContentProps) => {
  const { currentContent, setCurrentContent, currentHighlightedText, isReading } = useReading();
  const { toast } = useToast();
  const { difficulty, setDifficulty } = useDifficulty();
  const [isGenerating, setIsGenerating] = useState(false);
  const readingContentRef = useRef<HTMLDivElement>(null);

  // --- Voice Control States and Refs ---
  const [isListeningVoiceCommand, setIsListeningVoiceCommand] = useState(false);
  const [isProcessingVoiceCommand, setIsProcessingVoiceCommand] = useState(false);
  const [transcribedVoiceCommandText, setTranscribedVoiceCommandText] = useState<string>('');
  const [confirmationVoiceCommandMessage, setConfirmationVoiceCommandMessage] = useState<string>('');
  const [isPlayingVoiceResponse, setIsPlayingVoiceResponse] = useState(false);
  const audioRefVoiceResponse = useRef<HTMLAudioElement | null>(null);

  // --- Voice Control Handlers ---
  const handleVoiceResult = async (result: { action: string; topic?: string; parameters?: { difficulty?: string }; message?: string }) => {
    if (result.action === 'generateContent' && result.topic) {
      try {
        const difficultyParam = result.parameters?.difficulty;
        // Validate and sanitize difficulty (default to current UI difficulty if invalid or missing)
        const contentDifficulty = difficultyParam && /^[1-8]$/.test(difficultyParam)
          ? difficultyParam
          : difficulty; // Use current UI difficulty as fallback

        console.log(`Generating content about "${result.topic}" with difficulty "${contentDifficulty}"`);

        // Set confirmation message
        setConfirmationVoiceCommandMessage(result.message || `I'll find a reading article on ${result.topic} for you.`);

        // Convert numeric difficulty to server format
        const serverDifficulty = mapDifficultyToServer(contentDifficulty as DifficultyLevel);
        const content = await generateReadingContent(result.topic, serverDifficulty);
        setCurrentContent({ ...content, topic: result.topic }); // Preserve topic if needed
        // Removed toast notification for content generated by voice command
        // toast({
        //   title: 'Content Generated',
        //   description: `Generated content about "${result.topic}"`,
        // });
      } catch (error) {
        console.error('Error generating content from voice command:', error);
        setConfirmationVoiceCommandMessage('');
        // Removed toast notification for error generating content from voice command
        // toast({
        //   title: 'Error',
        //   description: 'Failed to generate content from voice command',
        //   variant: 'destructive',
        // });
      }
    } else if (result.message) {
      // Set confirmation message for non-content actions or general responses
      setConfirmationVoiceCommandMessage(result.message);
    } else {
      setConfirmationVoiceCommandMessage('I understood your request.');
    }
  };

  const handleAudioResponse = (audioData: string) => {
    if (!audioRefVoiceResponse.current) {
      audioRefVoiceResponse.current = new Audio();
    }

    // Create a blob URL from the base64 audio data
    const blob = new Blob([Buffer.from(audioData, 'base64')], { type: 'audio/mp3' });
    const url = URL.createObjectURL(blob);

    // Clean up old URL if it exists
    if (audioRefVoiceResponse.current.src) {
      URL.revokeObjectURL(audioRefVoiceResponse.current.src);
    }

    // Set the new audio source and play it
    audioRefVoiceResponse.current.src = url;
    audioRefVoiceResponse.current.onplay = () => setIsPlayingVoiceResponse(true);
    audioRefVoiceResponse.current.onended = () => setIsPlayingVoiceResponse(false);
    audioRefVoiceResponse.current.play().catch((err) => console.error('Error playing audio:', err));
  };

  // Set up enhanced voice recognition with GPT-4o
  const {
    isListening,
    isProcessing,
    transcribedText: enhancedTranscript,
    startListening,
    stopListening,
  } = useEnhancedVoice({
    onVoiceResult: handleVoiceResult,
    onAudioResponse: handleAudioResponse,
    onTranscript: (text) => setTranscribedVoiceCommandText(text),
    onError: (error) => {
      console.error('Voice recognition error:', error);
      setConfirmationVoiceCommandMessage('');
      // Removed toast notification for voice recognition error
      // toast({
      //   title: 'Voice Recognition Error',
      //   description: error.message,
      //   variant: 'destructive',
      // });
      // Reset voice command states on error
      setIsListeningVoiceCommand(false);
      setIsProcessingVoiceCommand(false);
    },
  });

  // Sync voice command states from hook
  useEffect(() => {
    setIsListeningVoiceCommand(isListening);
    setIsProcessingVoiceCommand(isProcessing);
    // Only update if enhancedTranscript is not empty, to avoid clearing on stop if there's no new transcript
    if (enhancedTranscript) {
      setTranscribedVoiceCommandText(enhancedTranscript);
    }
  }, [isListening, isProcessing, enhancedTranscript]);

  // Clean up audio resources when component unmounts
  useEffect(() => {
    return () => {
      if (audioRefVoiceResponse.current?.src) {
        URL.revokeObjectURL(audioRefVoiceResponse.current.src);
      }
    };
  }, []);

  const toggleVoiceCommandListening = () => {
    if (!isListeningVoiceCommand && !isProcessingVoiceCommand) { // Only start if currently idle
      // Clear previous transcript and confirmation before starting new listening session
      setTranscribedVoiceCommandText('');
      setConfirmationVoiceCommandMessage('');
      startListening();
    } else { // Stop if listening (or if processing, though usually processing can't be stopped manually)
      stopListening();
    }
  };
  // --- End Voice Control additions ---


  const generateNewContent = async () => {
    setIsGenerating(true);
    try {
      // Use a variety of topics for content generation
      const topics = [
        'gardening', 'cooking', 'travel', 'animals', 'history',
        'music', 'technology', 'health', 'science', 'nature'
      ];
      const randomTopic = topics[Math.floor(Math.random() * topics.length)];

      // Convert numeric difficulty to server format (easy, medium, hard)
      const serverDifficulty = mapDifficultyToServer(difficulty);
      console.log(`Generating new content about "${randomTopic}" with difficulty "${serverDifficulty}"`);

      const content = await generateReadingContent(randomTopic, serverDifficulty);
      setCurrentContent(content);
      // Removed toast notification for new content generation
      // toast({
      //   title: "New Content Generated",
      //   description: `Generated: ${content.title}`,
      // });
    } catch (error) {
      console.error("Error generating content:", error);
      // Removed toast notification for error generating new content
      // toast({
      //   title: "Error",
      //   description: "Failed to generate new content. Please try again.",
      //   variant: "destructive",
      // });
    } finally {
      setIsGenerating(false);
    }
  };

  // Toggle difficulty and automatically regenerate content with new difficulty
  const toggleDifficulty = async () => {
    // Cycle through difficulty levels 1-8
    const currentLevel = parseInt(difficulty);
    const newLevel = currentLevel < 8 ? currentLevel + 1 : 1;
    const newDifficulty = String(newLevel) as any;

    setDifficulty(newDifficulty);

    // Removed toast notification for difficulty change
    // toast({
    //   title: `Difficulty: Level ${newDifficulty}`,
    //   description: "Generating new content with updated difficulty level...",
    // });

    // Generate new content with the updated difficulty after a short delay
    setTimeout(async () => {
      setIsGenerating(true);
      try {
        // Attempt to preserve topic if possible, otherwise use random
        const currentTopic = currentContent?.topic || currentContent?.title.split(' ').slice(0, 2).join(' ').toLowerCase() || 'random';
        // Convert numeric difficulty to server format
        const serverDifficulty = mapDifficultyToServer(newDifficulty);
        console.log(`Generating content about "${currentTopic}" with difficulty "${serverDifficulty}"`);

        const content = await generateReadingContent(currentTopic, serverDifficulty);
        setCurrentContent(content);
      } catch (error) {
        console.error("Error generating content with new difficulty:", error);
        // Removed toast notification for error updating difficulty
        // toast({
        //   title: "Error",
        //   description: "Failed to update difficulty. Please try again.",
        //   variant: "destructive",
        // });
      } finally {
        setIsGenerating(false);
      }
    }, 500);
  };

  useEffect(() => {
    if (readingContentRef.current && currentContent) {
      try {
        // Ensure content is a string before proceeding
        let contentStr = typeof currentContent.content === 'string'
          ? currentContent.content
          : JSON.stringify(currentContent.content);

        // Remove any URLs in parentheses at the end of paragraphs
        contentStr = contentStr.replace(/\(\[?[\w\.]+\]?\(https?:\/\/[^\)]*\)\)/g, '');

        // Replace section headers like **Politics** with lead-in phrases
        contentStr = contentStr.replace(/\*\*([\w\s]+)\*\*/g, (match, topic) => {
          return `In ${topic.toLowerCase()},`;
        });

        // Create spans for text highlighting
        const paragraphs = contentStr.split('\n\n');

        readingContentRef.current.innerHTML = paragraphs
          .map(paragraph => {
            const sentences = paragraph.split('. ');
            const formattedSentences = sentences
              .map(sentence => `<span>${sentence}</span>`)
              .join('. ');

            return `<p>${formattedSentences}</p>`;
          })
          .join('');
      } catch (error) {
        console.error('Error formatting content:', error);
        // Fallback rendering in case of error
        if (typeof currentContent.content === 'string') {
          readingContentRef.current.innerHTML = `<p>${currentContent.content}</p>`;
        } else {
          readingContentRef.current.innerHTML = '<p>Unable to display content. Please try generating a new article.</p>';
        }
      }
    }
  }, [currentContent]);

  useEffect(() => {
    if (readingContentRef.current && currentHighlightedText && isReading) {
      // Remove previous highlights
      const spans = readingContentRef.current.querySelectorAll('span');
      spans.forEach(span => {
        span.classList.remove('text-primary', 'bg-primary/10', 'font-medium');
      });

      // Add highlight to matching span
      Array.from(spans).forEach(span => {
        if (span.textContent?.trim() === currentHighlightedText.trim()) {
          span.classList.add('text-primary', 'bg-primary/10', 'font-medium');

          // Scroll into view if needed
          const rect = span.getBoundingClientRect();

          if (readingContentRef.current) {
            const contentRect = readingContentRef.current.getBoundingClientRect();

            if (rect.top < contentRect.top || rect.bottom > contentRect.bottom) {
              span.scrollIntoView({ behavior: 'smooth', block: 'center' });
            }
          }
        }
      });
    }
  }, [currentHighlightedText, isReading]);

  if (!currentContent) return null;

  return (
    <Card className="mb-6">
      <CardContent className="p-6">
        <div className="flex items-center justify-between mb-4">
          <h2 className="text-lg font-medium">Select Your Topic</h2>
        </div>

        {/* Voice Command Feedback Section, similar to original VoiceControl.tsx */}
        {(transcribedVoiceCommandText || confirmationVoiceCommandMessage || isProcessingVoiceCommand) && (
          <div className="bg-secondary bg-opacity-30 rounded-lg p-3 flex items-center mb-4">
            <div className="flex items-center mr-3">
              {isPlayingVoiceResponse && (
                <div className="rounded-full bg-accent p-2 animate-pulse">
                  <Volume2 className="w-6 h-6 text-white" />
                </div>
              )}
            </div>

            <div className="flex-1">
              {isProcessingVoiceCommand ? (
                <div>
                  <p className="text-sm text-textColor opacity-70 mb-1">Processing voice command:</p>
                  <p className="font-medium">Thinking...</p>
                </div>
              ) : transcribedVoiceCommandText || confirmationVoiceCommandMessage ? (
                <div className={isPlayingVoiceResponse ? 'border-l-4 border-accent pl-3' : ''}>
                  <p className="text-sm text-textColor opacity-70 mb-1">
                    {isPlayingVoiceResponse ? 'AI Response:' : confirmationVoiceCommandMessage ? 'ReadAssist:' : 'I heard:'}
                  </p>
                  <p className="font-medium">
                    {isProcessingVoiceCommand || confirmationVoiceCommandMessage ? confirmationVoiceCommandMessage : transcribedVoiceCommandText}
                  </p>
                  {isPlayingVoiceResponse && (
                    <div className="mt-1 pt-1 border-t border-gray-200 text-sm text-textColor opacity-90 italic">
                      <p>ReadAssist is speaking...</p>
                    </div>
                  )}
                </div>
              ) : null}
            </div>
          </div>
        )}
        {/* End Voice Command Feedback Section */}

        <div className="mb-4 border-b border-secondary pb-2">
          <h3 className="font-semibold text-lg mb-2">{currentContent.title}</h3>
          <p className="text-sm text-textColor opacity-70 mb-1">
            Source: {currentContent.source} •
            {' '}{Math.round(currentContent.readingTime / 60)} min read •
            {' '}{currentContent.wordCount} words
          </p>
        </div>

        <div
          ref={readingContentRef}
          className="prose max-w-none text-lg leading-relaxed"
        >
          {/* Content will be injected via useEffect */}
        </div>

        {/* New row for action buttons at the bottom right */}
        <div className="flex justify-end space-x-2 mt-6"> {/* Added mt-6 for separation */}
          {/* Voice Command Button */}
          <Button
            onClick={toggleVoiceCommandListening}
            disabled={isPlayingVoiceResponse || isProcessingVoiceCommand}
            size="sm"
            className={`text-sm ${
              isListeningVoiceCommand ? 'bg-red-500 hover:bg-red-600' :
              isProcessingVoiceCommand ? 'bg-yellow-500 hover:bg-yellow-600' :
              'bg-[#F95A2C] hover:bg-[#E64E20] text-white border-0'
            }`}
          >
            <MicIcon className="w-4 h-4 mr-1" />
            {isListeningVoiceCommand ? 'Listening...' : isProcessingVoiceCommand ? 'Thinking...' : 'I want to read about..'}
          </Button>

          {/* New Content Button */}
          <Button
            onClick={generateNewContent}
            disabled={isGenerating}
            size="sm"
            className="text-sm bg-[#00C6AE] hover:bg-[#00B39E] text-white border-0"
          >
            <RefreshCw className="w-4 h-4 mr-1" />
            {isGenerating ? 'Generating...' : 'New Content'}
          </Button>
        </div>
      </CardContent>
    </Card>
  );
};

export default ReadingContent;